projet1/src/Entity/Quiz.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuizRepository")
 */
class Quiz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $niveau;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Theme", inversedBy="quizs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $theme;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Resultat", mappedBy="quiz")
     */
    private $resultats;

    public function __construct()
    {
        $this->resultats = new ArrayCollection();
        $this->utilisateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    /**
     * @return Collection|Resultat[]
     */
    public function getResultats(): Collection
    {
        return $this->resultats;
    }

    public function addResultat(Resultat $resultat): self
    {
        if (!$this->resultats->contains($resultat)) {
            $this->resultats[] = $resultat;
            $resultat->setQuiz($this);
        }

        return $this;
    }

    public function removeResultat(Resultat $resultat): self
    {
        if ($this->resultats->contains($resultat)) {
            $this->resultats->removeElement($resultat);
            // set the owning side to null (unless already changed)
            if ($resultat->getQuiz() === $this) {
                $resultat->setQuiz(null);
            }
        }

        return $this;
    }
    
}

projet1/src/Entity/Theme.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ThemeRepository")
 */
class Theme
{
/**
 * @ORM\Id()
 * @ORM\GeneratedValue()
 * @ORM\Column(type="integer")
 */
private $id;

/**
 * @ORM\Column(type="string", length=255)
 */
private $libelle;

/**
 *
 * @ORM\ManyToMany(targetEntity="Vocabulaire", mappedBy="themes")

 */
private $vocabulaires;

/**
 * @ORM\Column(type="string", length=255, nullable=true)
 */
private $Image;

/**
 * @ORM\OneToMany(targetEntity="App\Entity\Quiz", mappedBy="theme")
 */
private $quizs;

public function __construct()
{
    $this->vocabulaires = new ArrayCollection();
    $this->quizs = new ArrayCollection();
}

public function getId(): ?int
{
return $this->id;
}

public function getLibelle(): ?string
{
return $this->libelle;
}

public function setLibelle(string $libelle): self
{
$this->libelle = $libelle;

return $this;
}

/**
 * @return Collection|Vocabulaire[]
 */
public function getVocabulaires(): Collection
{
    return $this->vocabulaires;
}

public function addVocabulaire(Vocabulaire $vocabulaire): self
{
    if (!$this->vocabulaires->contains($vocabulaire)) {
        $this->vocabulaires[] = $vocabulaire;
        $vocabulaire->addTheme($this);
    }

    return $this;
}

public function removeVocabulaire(Vocabulaire $vocabulaire): self
{
    if ($this->vocabulaires->contains($vocabulaire)) {
        $this->vocabulaires->removeElement($vocabulaire);
        $vocabulaire->removeTheme($this);
    }

    return $this;
}

public function getImage()
{
    return $this->Image;
}

public function setImage( $Image)
{
    $this->Image = $Image;

    return $this;
}

/**
 * @return Collection|Quiz[]
 */
public function getQuizs(): Collection
{
    return $this->quizs;
}

public function addQuiz(Quiz $quiz): self
{
    if (!$this->quizs->contains($quiz)) {
        $this->quizs[] = $quiz;
        $quiz->setTheme($this);
    }

    return $this;
}

public function removeQuiz(Quiz $quiz): self
{
    if ($this->quizs->contains($quiz)) {
        $this->quizs->removeElement($quiz);
        // set the owning side to null (unless already changed)
        if ($quiz->getTheme() === $this) {
            $quiz->setTheme(null);
        }
    }

    return $this;
}
}

projet1/src/Controller/QuizController.php
<?php

namespace App\Controller;

use App\Entity\Quiz;
use App\Entity\Resultat;
use App\Entity\Realise;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class QuizController extends AbstractController
{
    /**
     * @Route("/quiz-ajouter", name="quiz-ajouter")
     */
    public function ajouter(Request $request)
    {
        $quiz = new Quiz();
        $form = $this->createFormBuilder($quiz)
            ->add('niveau', TextType::class)
            ->add('theme', EntityType::class, array(
                'class' => 'App\Entity\Theme',
                'choice_label' => 'libelle',
                'expanded' => false,
                'multiple' => false))
            ->add('save', SubmitType::class, array('label' => 'Ajouter'))
            ->getForm();

            if ($request->isMethod('POST')) {
                $form->handleRequest($request);
                if ($form->isValid()) {
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($quiz);
                    $em->flush();
                    return $this->redirectToRoute('quiz-liste');
                }
            }

        return $this->render('quiz/ajouter.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/quiz-liste", name="quiz-liste")
     */
    public function liste(Request $request)
    {
        $repository = $this->getDoctrine()->getManager()->getRepository(Quiz::class);

        $quiz = new Quiz();
        $form = $this->createFormBuilder($quiz)
            ->add('save', SubmitType::class, array('attr' => array('class' => 'btn btn-danger'), 'label' => 'Supprimer'))
            ->getForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $cocher = $request->request->get('cocher');
                foreach ($cocher as $i) {
                    $q = $repository->find($i);
                    $this->getDoctrine()->getManager()->remove($q);
                }
                $this->getDoctrine()->getManager()->flush();
            }
        }

        $quizs = $repository->findAll();

        return $this->render('quiz/liste.html.twig', ['form' => $form->createView(), 'quizs' => $quizs]);
    }

    /**
     * @Route("/quiz-modifier/{id}", name="quiz-modifier")
     */
    public function modifier(Request $request)
    {
        $repository = $this->getDoctrine()->getManager()->getRepository(Quiz::class);
        $quiz = $repository->find($request->get('id'));
        $form = $this->createFormBuilder($quiz)
            ->add('niveau', TextType::class)
            ->add('theme', EntityType::class, array(
                'class' => 'App\Entity\Theme',
                'choice_label' => 'libelle',
                'expanded' => false,
                'multiple' => false))
            ->add('save', SubmitType::class, array('label' => 'Modifier'))
            ->getForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($quiz);
                $em->flush();
            }
        }
        return $this->render('quiz/modifier.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/listeQuiz", name="listeQuiz")
     */
    public function listeQuiz()
    {
        $repository = $this->getDoctrine()->getManager()->getRepository(Quiz::class);

        $quizs = $repository->findAll();

        return $this->render('quiz/listeQuiz.html.twig', ['quizs' => $quizs]);
    }

    /**
     * @Route("/faireQuiz/{id}", name="faireQuiz")
     */
    public function faireQuiz(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $repositoryRealise = $em->getRepository(Realise::class);
        $ajd = new \DateTime('today');
        $estDejaFait = $repositoryRealise->findBy(array('utilisateur' => $this->getUser(), 'quiz' => $request->get('id'), 'date' => $ajd));

        if(!empty($estDejaFait)){
            $this->addFlash('erreur', 'Vous avez déjà réalisé le quiz aujourd\'hui !');
            return $this->redirectToRoute('listeQuiz');
        }
        
        $repository = $em->getRepository(Quiz::class);
        $quiz = $repository->find($request->get('id'));

        $afficherScore = "Score : ";

        if($request->isMethod('POST')){
            $bonnesreponses = 0;
            $contenu = array();

            $vocabulaires = $quiz->getTheme()->getVocabulaires()->toArray();

            foreach($vocabulaires as $v){
                $utilisateurreponse = $request->request->get($v->getId());
                if(strtolower($v->getAnglais()) == strtolower($utilisateurreponse)){
                    $bonnesreponses++;
                }
                $contenu = array_merge($contenu, [$v->getAnglais() => $utilisateurreponse]);
            }
            $pourcentage = round(100 * $bonnesreponses / sizeof($vocabulaires));
            $score = array("bonnesreponses" => $bonnesreponses, "nbquestions" => sizeof($vocabulaires), "pourcentage" => $pourcentage);
            
            $afficherScore = "Score : " . $bonnesreponses . " / " . sizeof($vocabulaires) . " (" . $pourcentage . " %)";

            $resultat = new Resultat();
            $resultat->setNote(json_encode($score));
            $resultat->setContenu(json_encode($contenu));
            $resultat->setUtilisateur($this->getUser());
            $resultat->setQuiz($quiz);
            $resultat->setDate(new \DateTime());
            $em->persist($resultat);

            $realise = new Realise();
            $realise->setUtilisateur($this->getUser());
            $realise->setQuiz($quiz);
            $ajd = new \DateTime('today');
            $realise->setDate($ajd);
            $em->persist($realise);
            $em->flush();
        }
        
        return $this->render('quiz/faireQuiz.html.twig', ['quiz' => $quiz, 'score' => $afficherScore]);
    }
}

projet1/templates/quiz/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<h1 class="text-center">Ajouter un quiz</h1>
    {{form_start(form)}}
    {{ form_errors(form) }}
    <div class="form-group">
        {{ form_row(form.niveau, {'label': 'Niveau : ', 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.theme, {'label': 'Thème : ', 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.save, {'attr' : {'class': 'btn btn-success'}}) }}
    </div>
    {{form_end(form)}}
</div>
{% endblock %}

projet1/templates/quiz/faireQuiz.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
<h1 class="text-center">Quiz {{quiz.theme.libelle}} - {{quiz.niveau}}</h1>
<h4>Donnez la traduction en anglais de ces mots :</h4>
<form action="{{path('faireQuiz', {'id' : quiz.id})}}" method="post">
{% for v in quiz.theme.vocabulaires %}
<label>{{v.francais}} :</label>
<input type="text" class="form-control" name="{{v.id}}">
{% endfor %}
<button type="submit" class="btn btn-success form-control mt-2">Valider</button>
</form>
<h5 class="text-center mt-3">{{score}}</h5>
</div>
{% endblock %}

projet1/templates/quiz/liste.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">
{{ form_start(form) }}
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th scope="col">Niveau</th>
                <th scope="col">Thème</th>
                <th scope="col">Modifier</th>
                <th scope="col">Supprimer</th>
            </tr>
        </thead>
        <tbody>
            {% for q in quizs %}
            <tr>
                <th scope="row">{{q.niveau}}</th>
                <th scope="row">{{q.theme.libelle}}</th>
                <td><a href="{{path('quiz-modifier',{'id':q.id})}}" class="btn btn-success mr-2">Modifier</a></td>
                <td><input type="checkbox" name="cocher[]"value="{{q.id}}"/></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
                <div class="d-flex justify-content-end">{{form_widget(form.save)}}</div>
            {{ form_end(form) }}
    </div>
{% endblock %}

projet1/templates/quiz/listeQuiz.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">
<h1 class="text-center">Liste des Quizs disponibles</h1>
<div class="row">
            {% for q in quizs %}
<div class="col-lg-4">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{asset('img/theme/')}}{{q.theme.image}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{q.theme.libelle}}</h5>
    <p class="card-text">{{q.niveau}}</p>
    <a href="{{path('faireQuiz', {'id' : q.id})}}" class="btn btn-success">Faire le quiz</a>
  </div>
</div>
</div>
            {% endfor %}
            </div>
    </div>
{% endblock %}

projet1/templates/quiz/modifier.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
        {{form_start(form)}}
    {{ form_errors(form) }}
    <div class="form-group">
        {{ form_row(form.niveau, {'label': 'Niveau : ', 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.theme, {'label': 'Thème : ', 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.save, {'attr' : {'class': 'btn btn-primary'}}) }}
    </div>
    {{form_end(form)}}
</div>
{% endblock %}